### PR TITLE
COMDOX-247: Migrate Admin Pattern Library from magento/devdocs

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) migrates the [Admin Pattern Library](https://devdocs.magento.com/guides/v2.4/pattern-library/bk-pattern.html) from the `devdocs.magento.com` site to the Adobe DevSite.

**Staging**: https://developer-stage.adobe.com/commerce/admin-developer/

## Affected pages

- Several

## Links to related PRs or Jira tickets

- COMDOX-247
- https://github.com/magento-commerce/devdocs/pull/3090

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My changes follow the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
I'm still trying to fix the size of the spinner .gif on this page: https://developer-stage.adobe.com/commerce/admin-developer/pattern-library/feedback-to-user/progress-indicator/#spinner.

I've posted a question in the #adobeio-devsite Slack and am waiting for a response.

**Comment by jeff-matthews** [comment]
Fixed the size of the spinner .gif by adding a new component (advised to do so by devsite team). Redeploying the branch to staging.

**Review by bdenham — APPROVED** [review]
Interesting. I hadn't seen the adding of a CustomImage as a way to fix sizing of an image. Just gif images? I'll have to research that later. Doesn't seem like a long-term solution, but if it works for now, that works for me.

**Comment by jeff-matthews** [comment]
Yeah, Tim recommended it to side-step whatever processing Gatsby does with images. I don't think it's exclusive to .gif files. Probably any image file that is small and not meant to be enlarged.

**Pull request merged**
